### ISSUE TITLE
fbp file generated with export feature is not recognized by soletta

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta-visual-editor#1]
fbp file generated using Export feature is not recognized by soletta, an error was returned while trying to convert the fbp file to c code. 

The fbp file contents is available from here: http://pastebin.com/N1MQwuqJ

The error returned by sol-fbp-generator is shown below:

sol-fbp-generator -j builtins.json -j test.json slv_fibonacci.fbp slv_fibonacci.cpp
./slv_fibonacci.fbp:1:29 Port 'OPERAND' from node type 'int/addition' is an array port and no index was given'
ERR: ./src/bin/sol-fbp-generator/main.c:794 generate() Couldn't generate root type function

Steps to reproduce the error: 
- The test is based in replicate the soletta example located in /soletta/src/samples/flow/basic/fibonacci.fbp
- The aspect of the slv diagram connections is founded in the attached image:

![fibonacci_slv_diagram](https://cloud.githubusercontent.com/assets/13384596/9862193/dea44a9e-5afc-11e5-8544-acfe947cb460.png)

Thank you.

**Comment by davidmaxwaterman** [comment]
I have been told that array ports are a feature for a future version of SLV. However, my fix above should work for the 'sum' node in the above case.

**Comment by davidmaxwaterman** [comment]
OK, I think this is now fixed.

**Comment by dborquez** [comment]
The example was replicated using the patches provided in:
commit abbd7cdbf752dd51407bc33623314a646ca289f7
commit 0c93015d7c8a74e6d38c419b301ef6ccd4a484cb
commit ffa42a3814b3ba6abf55a948106f5ac90d195335

The issue is resolved.

**Comment by dborquez** [comment]
The example was replicated using the patches provided in:

commit abbd7cdbf752dd51407bc33623314a646ca289f7
commit 0c93015d7c8a74e6d38c419b301ef6ccd4a484cb
commit ffa42a3814b3ba6abf55a948106f5ac90d195335

The issue is resolved.
