### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by otcyanglei** [solettaproject/soletta-visual-editor#9]
I tried to build soletta-visual-editor. By following the README, I run "npm install" to install some dependencies. 
However, it failed and some dependencies cannot be installed. This blocked the next steps to build. 

My environment: 
Linux desktop: Ubuntu 14.04 LTS
The “node” in my system is linked to “nodejs”. nodejs version: 0.10.25
The proxy and https-proxy in npm are set correctly

**Comment by otcyanglei** [comment]
somehow I cannot upload the npm install log file. I post the log here: 
///////////////////////////////////////////////////////////////////////////////////////////////////////////

npm http 304 https://registry.npmjs.org/brace-expansion

> wct-local@1.7.0 postinstall /home/yanglei/workspace/soletta-visual-editor/node_modules /web-component-tester/node_modules/wct-local
> node scripts/postinstall.js

---

## selenium-standalone installation starting

---

selenium install:
from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar

## to: /home/yanglei/workspace/soletta-visual-editor/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/2.47.1-server.jar

chrome install:
from: http://chromedriver.storage.googleapis.com/2.18/chromedriver_linux64.zip
to: /home/yanglei/workspace/soletta-visual-editor/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.18-x64-chromedriver

---

## selenium-standalone installation finished

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete](net.js:892:19)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 8
npm ERR! not ok code 0

///////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by davidmaxwaterman** [comment]
I just tried this, and it works for me.

However, I'm not behind a proxy, and I'm using node v0.12.3 in Ubuntu 15.10.

Perhaps it's related to this issue :

https://github.com/Polymer/wct-sauce/issues/5

You might try to comment out the web-component-tester line in package.json and see if it completes without that. Selenium is for the tests, so you might get away without them...your call.

**Comment by davidmaxwaterman** [comment]
Can I assume this issue is the same as described on the referenced wct-sauce issue? If so, I will close this.
Regards.

**Comment by davidmaxwaterman** [comment]
no response to previous comment, after almost a whole month, so closing.
